Update zod to prevent incompatibilities _again_
Basically cb5fe58 again, without the version bump `yarn tsc` fails with
mysterious errors like the one from below:

```
$ yarn tsc
plugins/s3-viewer-backend/src/permissions/rules.ts:9:3 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(rule: { name: string; description: string; resourceRef: PermissionResourceRef<BucketDetails, BucketDetailsFilter, "s3-viewer.bucket", "s3-viewer">; paramsSchema?: ZodType<...> | undefined; apply(resource: BucketDetails, params: undefined): boolean; toQuery(params: undefined): PermissionCriteria<...>; }): PermissionRule<...>', gave the following error.
    Type 'ZodObject<{ owners: ZodArray<ZodString>; }, $strip>' is missing the following properties from type 'ZodType<undefined, ZodTypeDef, undefined>': _type, _parse, _getType, _getOrReturnCtx, and 7 more.
  Overload 2 of 2, '(rule: PermissionRule<unknown, unknown, string, undefined>): PermissionRule<unknown, unknown, string, undefined>', gave the following error.
    Type 'ZodObject<{ owners: ZodArray<ZodString>; }, $strip>' is missing the following properties from type 'ZodType<undefined, ZodTypeDef, undefined>': _type, _parse, _getType, _getOrReturnCtx, and 7 more.

9   paramsSchema: z.object({
```

This matches the same change done upstream in https://github.com/backstage/backstage/pull/33399.